import "dotenv/config";
import { PrismaClient } from "../src/generated/prisma";
import { PrismaPg } from "@prisma/adapter-pg";
import pg from "pg";

const pool = new pg.Pool({ connectionString: process.env.DATABASE_URL });
const adapter = new PrismaPg(pool);
const prisma = new PrismaClient({ adapter });

type Cat = "EXPLICIT" | "STRONG" | "MODERATE" | "WEAK" | "FRINGE";

function calcJobs(announced: number, cat: Cat) {
  const weights: Record<Cat, { conservative: number; core: number; upper: number }> = {
    EXPLICIT:  { conservative: 1.0,  core: 1.0,  upper: 1.0  },
    STRONG:    { conservative: 0.0,  core: 0.75, upper: 1.0  },
    MODERATE:  { conservative: 0.0,  core: 0.40, upper: 0.70 },
    WEAK:      { conservative: 0.0,  core: 0.15, upper: 0.35 },
    FRINGE:    { conservative: 0.0,  core: 0.05, upper: 0.15 },
  };
  const w = weights[cat];
  return {
    conservative: Math.round(announced * w.conservative),
    core: Math.round(announced * w.core),
    upper: Math.round(announced * w.upper),
  };
}

const coreWeights: Record<Cat, number> = {
  EXPLICIT: 1.0, STRONG: 0.75, MODERATE: 0.40, WEAK: 0.15, FRINGE: 0.05,
};

type EventType = "AI_LAYOFF" | "ROBOT_LAYOFF" | "AI_JOB_CREATED" | "PRODUCTIVITY_GAIN";

interface EventData {
  company: string;
  jobs: number;
  date: string;
  country: string;
  industry: string;
  category: Cat;
  eventType: EventType;
  url: string;
  sourceDomain: string;
  sourceName: string;
  title: string;
  summary: string;
}

interface ProductivityClaimData {
  companyName: string;
  country: string;
  industry: string;
  claim: string;
  claimType: string;
  estimatedImpact: string;
  confidence: number;
  sourceUrl: string;
  publishedAt: string;
}

// ===== PRODUCTIVITY GAIN EVENTS =====
const events: EventData[] = [

  // --- Klarna: AI Customer Service ---
  {
    company: "Klarna",
    jobs: 0,
    date: "2024-02-27",
    country: "SE",
    industry: "Financial Services/Fintech",
    category: "EXPLICIT",
    eventType: "PRODUCTIVITY_GAIN",
    url: "https://www.klarna.com/international/press/klarna-ai-assistant-handles-two-thirds-of-customer-service-chats-in-its-first-month/",
    sourceDomain: "klarna.com",
    sourceName: "Klarna",
    title: "Klarna AI assistant handles two-thirds of customer service chats in first month",
    summary: "Klarna's OpenAI-powered AI assistant handled 2.3 million conversations in its first month (two-thirds of all customer service chats), equivalent to 700 full-time agents. Resolution time dropped from 11 minutes to under 2 minutes. Repeat inquiries fell 25%. Projected $40M profit improvement in 2024.",
  },
  {
    company: "Klarna",
    jobs: 0,
    date: "2025-05-14",
    country: "SE",
    industry: "Financial Services/Fintech",
    category: "EXPLICIT",
    eventType: "PRODUCTIVITY_GAIN",
    url: "https://www.cnbc.com/2025/05/14/klarna-ceo-says-ai-helped-company-shrink-workforce-by-40percent.html",
    sourceDomain: "cnbc.com",
    sourceName: "CNBC",
    title: "Klarna CEO says AI helped shrink workforce by 40%, customer service costs down 40%",
    summary: "Klarna CEO reported AI helped reduce headcount by 40% through attrition (from ~5,000 to ~3,000). Customer service cost per transaction dropped 40% from $0.32 to $0.19. 90% of staff use AI daily. AI handles ~1.3M conversations/month equivalent to 800+ full-time agents.",
  },

  // --- GitHub Copilot: Developer Productivity ---
  {
    company: "GitHub (Microsoft)",
    jobs: 0,
    date: "2024-02-14",
    country: "US",
    industry: "Technology/Software",
    category: "STRONG",
    eventType: "PRODUCTIVITY_GAIN",
    url: "https://arxiv.org/abs/2302.06590",
    sourceDomain: "arxiv.org",
    sourceName: "arXiv (Peer-reviewed study)",
    title: "GitHub Copilot study: developers completed tasks 55.8% faster",
    summary: "Controlled experiment found developers using GitHub Copilot completed coding tasks 55.8% faster (1h11m vs 2h41m). Task completion rate: 78% with Copilot vs 70% without. Copilot now writes ~46% of code for users, with 88% acceptance rate. Over 15 million developers using Copilot by early 2025.",
  },

  // --- Google: AI-Generated Code ---
  {
    company: "Google",
    jobs: 0,
    date: "2024-10-29",
    country: "US",
    industry: "Technology",
    category: "STRONG",
    eventType: "PRODUCTIVITY_GAIN",
    url: "https://www.itpro.com/technology/artificial-intelligence/sundar-pichai-says-more-than-25-percent-of-googles-code-is-now-generated-by-ai-and-its-a-big-hint-at-the-future-of-software-development",
    sourceDomain: "itpro.com",
    sourceName: "IT Pro",
    title: "Google CEO: over 25% of new Google code is now AI-generated",
    summary: "Sundar Pichai revealed during Q3 2024 earnings call that more than 25% of all new code at Google is generated by AI, then reviewed and accepted by engineers. Pichai cited ~10% improvement in engineering velocity. Code is generated by internal Gemini-based tools.",
  },

  // --- JPMorgan Chase: AI Productivity ---
  {
    company: "JPMorgan Chase",
    jobs: 0,
    date: "2024-08-01",
    country: "US",
    industry: "Banking/Finance",
    category: "STRONG",
    eventType: "PRODUCTIVITY_GAIN",
    url: "https://www.klover.ai/jpmorgan-ai-strategy-chasing-ai-dominance/",
    sourceDomain: "klover.ai",
    sourceName: "Klover AI",
    title: "JPMorgan's COiN system saves 360,000 work hours annually; LLM Suite reaches 140,000 employees",
    summary: "JPMorgan's Contract Intelligence (COiN) system processes 12,000 commercial credit agreements in seconds, saving 360,000 work hours annually. LLM Suite launched August 2024, reaching 140,000 employees (nearly half the workforce). AI productivity in deployed areas rose from 3% to 6%. $1.5B annual business value from AI initiatives.",
  },

  // --- Goldman Sachs: AI IPO Prospectus ---
  {
    company: "Goldman Sachs",
    jobs: 0,
    date: "2025-03-01",
    country: "US",
    industry: "Banking/Finance",
    category: "STRONG",
    eventType: "PRODUCTIVITY_GAIN",
    url: "https://fortune.com/2026/03/03/goldman-earnings-ai-anxiety-no-meaningful-impact-productivity-economy-30-percent-in-2-areas/",
    sourceDomain: "fortune.com",
    sourceName: "Fortune",
    title: "Goldman Sachs: AI completes 95% of IPO prospectus in minutes, 30% productivity boost in two use cases",
    summary: "Goldman CEO David Solomon demonstrated AI completing 95% of an IPO prospectus in minutes — work that previously required a six-person team two weeks. Goldman found a median 30% productivity gain in two specific use cases. Plans to deploy thousands of autonomous AI coding agents with 3-4x productivity projections.",
  },

  // --- Deutsche Bank: AI Developer Tools ---
  {
    company: "Deutsche Bank",
    jobs: 0,
    date: "2024-09-01",
    country: "DE",
    industry: "Banking/Finance",
    category: "MODERATE",
    eventType: "PRODUCTIVITY_GAIN",
    url: "https://cloud.google.com/blog/topics/financial-services/deutsche-bank-delivers-ai-powered-financial-research-with-db-lumina",
    sourceDomain: "cloud.google.com",
    sourceName: "Google Cloud Blog",
    title: "Deutsche Bank: 6,000 developers save 1.5-2.5 hours weekly with AI; DB Lumina saves analysts 2 hours per report",
    summary: "Deutsche Bank has 6,000+ developers using AI coding assistants (Gemini Code Assist, GitHub Copilot), saving 1.5-2.5 hours weekly per developer. DB Lumina AI research tool (launched Sept 2024) used by 5,000 staff saves analysts 30-45 minutes on earnings templates and up to 2 hours on research reports.",
  },

  // --- Microsoft Copilot: Enterprise Productivity ---
  {
    company: "Microsoft",
    jobs: 0,
    date: "2024-10-17",
    country: "US",
    industry: "Technology/Software",
    category: "STRONG",
    eventType: "PRODUCTIVITY_GAIN",
    url: "https://www.microsoft.com/en-us/microsoft-365/blog/2024/10/17/microsoft-365-copilot-drove-up-to-353-roi-for-small-and-medium-businesses-new-study/",
    sourceDomain: "microsoft.com",
    sourceName: "Microsoft",
    title: "Microsoft 365 Copilot: up to 353% ROI, 9.4% revenue increase per seller, 29% document productivity gain",
    summary: "Forrester TEI study found Microsoft 365 Copilot delivered 112-457% ROI. Microsoft's own sales org saw 9.4% revenue increase per seller and 20% higher close rates among heavy users. Document collaboration productivity improved 29%. Administrative loads decreased 23% in healthcare. 60%+ of Fortune 500 adopted Copilot by Q1 2024.",
  },

  // --- Amazon: Warehouse Robotics Throughput ---
  {
    company: "Amazon",
    jobs: 0,
    date: "2024-10-01",
    country: "US",
    industry: "Retail/Logistics",
    category: "STRONG",
    eventType: "PRODUCTIVITY_GAIN",
    url: "https://www.aboutamazon.com/news/operations/amazon-robotics-robots-fulfillment-center",
    sourceDomain: "aboutamazon.com",
    sourceName: "About Amazon",
    title: "Amazon: 1M+ robots boost throughput 25-50%, packages per employee up 22x over decade",
    summary: "Amazon now operates 1M+ robots across 300+ fulfillment centers. Automated centers see 25-50% throughput improvement. Sequoia system identifies and stores inventory 75% faster. Packages shipped per employee per year climbed from 175 to nearly 3,870 over the past decade (22x increase). Expected $12.6B in automation savings 2025-2027.",
  },

  // --- IKEA: AI Chatbot Revenue Uplift ---
  {
    company: "IKEA",
    jobs: 0,
    date: "2024-06-01",
    country: "SE",
    industry: "Retail/Furniture",
    category: "STRONG",
    eventType: "PRODUCTIVITY_GAIN",
    url: "https://sevenfour.digital/how-ikeas-use-of-ai-resulted-in-a-1-4-billion-revenue-uplift-with-no-layoffs/",
    sourceDomain: "sevenfour.digital",
    sourceName: "SevenFour Digital",
    title: "IKEA's AI chatbot drives $1.4B revenue uplift with no layoffs; 8,500 workers retrained",
    summary: "IKEA deployed an AI chatbot for customer service and instead of cutting jobs, retrained 8,500 call centre workers into interior design advisors and other higher-value roles. The shift contributed to a $1.4 billion revenue uplift. AI also improved demand forecasting accuracy significantly.",
  },

  // --- H&M: AI Inventory & Supply Chain ---
  {
    company: "H&M",
    jobs: 0,
    date: "2025-09-01",
    country: "SE",
    industry: "Retail/Fashion",
    category: "STRONG",
    eventType: "PRODUCTIVITY_GAIN",
    url: "https://ctomagazine.com/ai-at-hm-the-tech-strategy-behind-its-transformation/",
    sourceDomain: "ctomagazine.com",
    sourceName: "CTO Magazine",
    title: "H&M: AI drives 30% profit uplift, 25% overstock reduction, forecasting accuracy to 85-90%",
    summary: "H&M's AI-driven inventory management delivered 30% profit uplift from streamlined inventory. Overstock reduced 25%, sell-through rates climbed 15-20%. Forecasting accuracy reached 85-90%, reducing stockouts by 14%. Q3 2025 operating profit jumped 40%. 270-person AI unit built. Energy costs cut 14% via AI in pilot stores.",
  },

  // --- Unilever: Manufacturing AI ---
  {
    company: "Unilever",
    jobs: 0,
    date: "2024-12-01",
    country: "GB",
    industry: "Consumer Goods/Manufacturing",
    category: "STRONG",
    eventType: "PRODUCTIVITY_GAIN",
    url: "https://www.unilever.com/news/news-search/2025/how-were-unlocking-operational-efficiencies-and-net-productivity-through-ai/",
    sourceDomain: "unilever.com",
    sourceName: "Unilever",
    title: "Unilever: 27% productivity improvement across AI-deployed factories, 41% waste reduction",
    summary: "At three of four showcased Unilever sites, productivity improved 27% between 2020-2024, waste reduction improved 41%. At Kilbourn (largest condiments factory), OEE scores increased 16% and production waste reduced 42%. 23,000 employees trained in AI by end of 2024. AI 100+ Accelerator launched April 2025.",
  },

  // --- Procter & Gamble: AI Supply Chain ---
  {
    company: "Procter & Gamble",
    jobs: 0,
    date: "2025-01-01",
    country: "US",
    industry: "Consumer Goods/Manufacturing",
    category: "STRONG",
    eventType: "PRODUCTIVITY_GAIN",
    url: "https://www.klover.ai/procter-gamble-ai-strategy-path-to-ai-dominance-consumer-goods/",
    sourceDomain: "klover.ai",
    sourceName: "Klover AI",
    title: "P&G: AI Control Tower cuts truck waste 15%, predictive AI slashes production waste 80%, $100M+ media savings",
    summary: "P&G's Supply Chain 3.0 targets $1.5B in annual gross productivity savings. AI-driven logistics 'Control Tower' reduced inefficient truck movements by 15%. Predictive AI cut waste by up to 80% on key production lines. Autonomous media-buying agents save $100M+ annually in a single product division.",
  },

  // --- BMW: Virtual Factory ---
  {
    company: "BMW",
    jobs: 0,
    date: "2025-03-01",
    country: "DE",
    industry: "Automotive/Manufacturing",
    category: "MODERATE",
    eventType: "PRODUCTIVITY_GAIN",
    url: "https://www.press.bmwgroup.com/global/article/detail/T0450699EN/bmw-group-scales-virtual-factory?language=en",
    sourceDomain: "press.bmwgroup.com",
    sourceName: "BMW Group Press",
    title: "BMW Virtual Factory: collision checks reduced from 4 weeks to 3 days, 30% planning cost reduction projected",
    summary: "BMW's Virtual Factory reduces production planning costs by up to 30%. Collision checks that required almost 4 weeks of real testing now take just 3 days virtually. Plant Regensburg uses end-to-end AI-controlled robots for automated surface inspection in series production — a world first.",
  },

  // --- Radiology AI: Diagnostic Speed ---
  {
    company: "Healthcare AI (Global)",
    jobs: 0,
    date: "2025-01-01",
    country: "GLOBAL",
    industry: "Healthcare/Radiology",
    category: "STRONG",
    eventType: "PRODUCTIVITY_GAIN",
    url: "https://www.philips.com/a-w/about/news/archive/features/2025/ai-in-radiology-three-keys-to-real-world-impact.html",
    sourceDomain: "philips.com",
    sourceName: "Philips",
    title: "Radiology AI: 15.5% average boost in report completion efficiency, up to 40% for some radiologists",
    summary: "Studies show AI delivers an average 15.5% boost in radiograph report completion efficiency, with some radiologists achieving 40% gains. At KMC Manipal Hospital, AI-enabled CT workflows serve 20-30 more patients daily. AI-based breast cancer detection achieved 90% sensitivity vs 78% for radiologists alone.",
  },

  // --- OECD: Economy-Wide AI Productivity Assessment ---
  {
    company: "OECD (G7 Assessment)",
    jobs: 0,
    date: "2025-06-01",
    country: "GLOBAL",
    industry: "Economic Research",
    category: "MODERATE",
    eventType: "PRODUCTIVITY_GAIN",
    url: "https://www.oecd.org/en/publications/macroeconomic-productivity-gains-from-artificial-intelligence-in-g7-economies_a5319ab5-en.html",
    sourceDomain: "oecd.org",
    sourceName: "OECD",
    title: "OECD: AI could add 0.4-1.3 percentage points to annual labour productivity growth in G7 economies",
    summary: "OECD G7 report estimates AI could add 0.4-1.3 percentage points to annual aggregate labour productivity growth in high-exposure countries over a 10-year horizon. However, actual 2024 OECD-wide productivity growth was only 0.4%, and AI impact is 'not yet evident in the productivity statistics' at macro level.",
  },
];

// ===== PRODUCTIVITY CLAIMS (for ProductivityClaim model) =====
const claims: ProductivityClaimData[] = [
  {
    companyName: "Klarna",
    country: "SE",
    industry: "Financial Services/Fintech",
    claim: "AI assistant handles two-thirds of all customer service chats (~2.3M conversations/month), equivalent to 700 full-time agents. Resolution time dropped from 11 minutes to under 2 minutes. Cost per transaction fell 40% ($0.32 to $0.19).",
    claimType: "MEASURED_RESULT",
    estimatedImpact: "Equivalent to 700-800 FTE agents; $40M projected profit improvement in 2024",
    confidence: 0.95,
    sourceUrl: "https://www.klarna.com/international/press/klarna-ai-assistant-handles-two-thirds-of-customer-service-chats-in-its-first-month/",
    publishedAt: "2024-02-27",
  },
  {
    companyName: "GitHub (Microsoft)",
    country: "US",
    industry: "Technology/Software",
    claim: "Controlled study: developers completed tasks 55.8% faster with GitHub Copilot (1h11m vs 2h41m). Copilot now writes ~46% of code for users with 88% acceptance rate. 15M+ developers using it.",
    claimType: "PEER_REVIEWED_STUDY",
    estimatedImpact: "55.8% faster task completion for developers",
    confidence: 0.90,
    sourceUrl: "https://arxiv.org/abs/2302.06590",
    publishedAt: "2024-02-14",
  },
  {
    companyName: "Google",
    country: "US",
    industry: "Technology",
    claim: "CEO Sundar Pichai stated 25%+ of all new Google code is AI-generated, reviewed by engineers. ~10% improvement in engineering velocity reported.",
    claimType: "EXECUTIVE_STATEMENT",
    estimatedImpact: "25% of new code AI-generated; 10% engineering velocity boost",
    confidence: 0.85,
    sourceUrl: "https://www.itpro.com/technology/artificial-intelligence/sundar-pichai-says-more-than-25-percent-of-googles-code-is-now-generated-by-ai-and-its-a-big-hint-at-the-future-of-software-development",
    publishedAt: "2024-10-29",
  },
  {
    companyName: "JPMorgan Chase",
    country: "US",
    industry: "Banking/Finance",
    claim: "COiN system processes 12,000 commercial credit agreements in seconds, saving 360,000 work hours annually. LLM Suite deployed to 140,000 employees. Productivity in AI-deployed areas rose from 3% to 6%.",
    claimType: "MEASURED_RESULT",
    estimatedImpact: "360,000 work hours saved annually; $1.5B annual AI business value",
    confidence: 0.85,
    sourceUrl: "https://www.klover.ai/jpmorgan-ai-strategy-chasing-ai-dominance/",
    publishedAt: "2024-08-01",
  },
  {
    companyName: "Goldman Sachs",
    country: "US",
    industry: "Banking/Finance",
    claim: "AI completes 95% of IPO prospectus in minutes (previously 2 weeks for a 6-person team). 30% median productivity gain in two specific use cases. No meaningful economy-wide AI-productivity relationship found yet.",
    claimType: "EXECUTIVE_STATEMENT",
    estimatedImpact: "95% of IPO prospectus automated; 30% gain in targeted use cases",
    confidence: 0.80,
    sourceUrl: "https://fortune.com/2026/03/03/goldman-earnings-ai-anxiety-no-meaningful-impact-productivity-economy-30-percent-in-2-areas/",
    publishedAt: "2025-03-01",
  },
  {
    companyName: "Deutsche Bank",
    country: "DE",
    industry: "Banking/Finance",
    claim: "6,000+ developers using AI coding assistants save 1.5-2.5 hours per week. DB Lumina AI research tool (5,000 users) saves analysts 30-45 min on earnings templates, up to 2 hours on full research reports.",
    claimType: "MEASURED_RESULT",
    estimatedImpact: "6,000 developers x 1.5-2.5 hrs/week = 9,000-15,000 hours saved weekly",
    confidence: 0.80,
    sourceUrl: "https://cloud.google.com/blog/topics/financial-services/deutsche-bank-delivers-ai-powered-financial-research-with-db-lumina",
    publishedAt: "2024-09-01",
  },
  {
    companyName: "Microsoft",
    country: "US",
    industry: "Technology/Software",
    claim: "Microsoft 365 Copilot: Forrester TEI study found 112-457% ROI. Internal sales org saw 9.4% revenue/seller increase, 20% higher close rates. Document collaboration +29%. Healthcare admin loads -23%. 60%+ Fortune 500 adopted.",
    claimType: "COMMISSIONED_STUDY",
    estimatedImpact: "112-457% ROI; 9.4% revenue per seller; 29% document productivity",
    confidence: 0.75,
    sourceUrl: "https://www.microsoft.com/en-us/microsoft-365/blog/2024/10/17/microsoft-365-copilot-drove-up-to-353-roi-for-small-and-medium-businesses-new-study/",
    publishedAt: "2024-10-17",
  },
  {
    companyName: "Amazon",
    country: "US",
    industry: "Retail/Logistics",
    claim: "1M+ warehouse robots. Automated centers see 25-50% throughput boost. Sequoia system stores inventory 75% faster. Packages per employee per year: 175 to 3,870 over a decade (22x). Expected $12.6B savings 2025-2027.",
    claimType: "MEASURED_RESULT",
    estimatedImpact: "25-50% throughput increase; 22x packages/employee over decade; $12.6B projected savings",
    confidence: 0.85,
    sourceUrl: "https://www.aboutamazon.com/news/operations/amazon-robotics-robots-fulfillment-center",
    publishedAt: "2024-10-01",
  },
  {
    companyName: "IKEA",
    country: "SE",
    industry: "Retail/Furniture",
    claim: "AI chatbot deployed for customer service. Instead of cutting jobs, 8,500 call centre workers retrained into interior design advisors. Contributed to $1.4B revenue uplift. Improved demand forecasting accuracy.",
    claimType: "MEASURED_RESULT",
    estimatedImpact: "$1.4B revenue uplift; 8,500 workers upskilled (no layoffs)",
    confidence: 0.75,
    sourceUrl: "https://sevenfour.digital/how-ikeas-use-of-ai-resulted-in-a-1-4-billion-revenue-uplift-with-no-layoffs/",
    publishedAt: "2024-06-01",
  },
  {
    companyName: "H&M",
    country: "SE",
    industry: "Retail/Fashion",
    claim: "AI inventory management: 30% profit uplift, 25% overstock reduction, sell-through rates +15-20%, forecasting accuracy 85-90%, stockouts -14%. Q3 2025 operating profit jumped 40%. Energy costs cut 14% in pilot stores.",
    claimType: "MEASURED_RESULT",
    estimatedImpact: "30% profit uplift; 25% less overstock; Q3 2025 op profit +40%",
    confidence: 0.80,
    sourceUrl: "https://ctomagazine.com/ai-at-hm-the-tech-strategy-behind-its-transformation/",
    publishedAt: "2025-09-01",
  },
  {
    companyName: "Unilever",
    country: "GB",
    industry: "Consumer Goods/Manufacturing",
    claim: "27% productivity improvement across AI-deployed factories (2020-2024). Waste reduction improved 41%. Kilbourn factory: OEE +16%, production waste -42%. 23,000 employees trained in AI.",
    claimType: "MEASURED_RESULT",
    estimatedImpact: "27% productivity gain; 41% waste reduction across deployed sites",
    confidence: 0.85,
    sourceUrl: "https://www.unilever.com/news/news-search/2025/how-were-unlocking-operational-efficiencies-and-net-productivity-through-ai/",
    publishedAt: "2024-12-01",
  },
  {
    companyName: "Procter & Gamble",
    country: "US",
    industry: "Consumer Goods/Manufacturing",
    claim: "AI logistics 'Control Tower' reduced inefficient truck movements 15%. Predictive AI slashed production waste up to 80% on key lines. Autonomous media-buying agents save $100M+/year in one division. Supply Chain 3.0 targets $1.5B annual savings.",
    claimType: "MEASURED_RESULT",
    estimatedImpact: "15% truck waste reduction; 80% production waste cut; $100M+ media savings",
    confidence: 0.80,
    sourceUrl: "https://www.klover.ai/procter-gamble-ai-strategy-path-to-ai-dominance-consumer-goods/",
    publishedAt: "2025-01-01",
  },
  {
    companyName: "BMW",
    country: "DE",
    industry: "Automotive/Manufacturing",
    claim: "Virtual Factory reduces production planning costs by up to 30%. Collision checks reduced from 4 weeks real testing to 3 days virtual simulation. First car plant with end-to-end AI-controlled surface inspection in series production.",
    claimType: "COMPANY_REPORT",
    estimatedImpact: "30% planning cost reduction; collision checks 4 weeks to 3 days",
    confidence: 0.75,
    sourceUrl: "https://www.press.bmwgroup.com/global/article/detail/T0450699EN/bmw-group-scales-virtual-factory?language=en",
    publishedAt: "2025-03-01",
  },
  {
    companyName: "Healthcare AI (Radiology)",
    country: "GLOBAL",
    industry: "Healthcare/Radiology",
    claim: "Average 15.5% boost in radiograph report completion efficiency, up to 40% for some radiologists. AI breast cancer detection: 90% sensitivity vs 78% for radiologists. KMC Manipal: 20-30 additional patients served daily.",
    claimType: "PEER_REVIEWED_STUDY",
    estimatedImpact: "15.5% average efficiency gain; up to 40% for top performers",
    confidence: 0.85,
    sourceUrl: "https://www.philips.com/a-w/about/news/archive/features/2025/ai-in-radiology-three-keys-to-real-world-impact.html",
    publishedAt: "2025-01-01",
  },
  {
    companyName: "OECD (G7 Assessment)",
    country: "GLOBAL",
    industry: "Economic Research",
    claim: "AI could add 0.4-1.3 percentage points to annual labour productivity growth in G7 economies over 10 years. But actual 2024 OECD productivity growth was only 0.4%, and AI impact is 'not yet evident in the productivity statistics'.",
    claimType: "ECONOMIC_REPORT",
    estimatedImpact: "0.4-1.3 ppt annual labour productivity growth (projected, not yet measured at macro level)",
    confidence: 0.70,
    sourceUrl: "https://www.oecd.org/en/publications/macroeconomic-productivity-gains-from-artificial-intelligence-in-g7-economies_a5319ab5-en.html",
    publishedAt: "2025-06-01",
  },
];

async function main() {
  let eventsCreated = 0;
  let eventsSkipped = 0;
  let claimsCreated = 0;
  let claimsSkipped = 0;

  // ===== INSERT EVENTS =====
  for (const ev of events) {
    const existing = await prisma.event.findFirst({
      where: {
        companyName: ev.company,
        eventType: ev.eventType,
        publicSummary: { contains: ev.summary.substring(0, 50) },
      },
    });

    if (existing) {
      console.log(`[SKIP EVENT] ${ev.company}: ${ev.title.substring(0, 60)}... — already exists`);
      eventsSkipped++;
      continue;
    }

    // Upsert company
    const company = await prisma.company.upsert({
      where: { name: ev.company },
      update: { industry: ev.industry, country: ev.country },
      create: { name: ev.company, industry: ev.industry, country: ev.country },
    });

    // Upsert source
    const source = await prisma.source.upsert({
      where: { domain: ev.sourceDomain },
      update: {},
      create: { domain: ev.sourceDomain, name: ev.sourceName, type: "news" },
    });

    // Handle article URL uniqueness
    let articleUrl = ev.url;
    const existingArticle = await prisma.article.findUnique({ where: { url: articleUrl } });
    if (existingArticle && existingArticle.title !== ev.title) {
      articleUrl = `${ev.url}#${ev.company.toLowerCase().replace(/[^a-z0-9]/g, "-")}`;
    }

    const article = await prisma.article.upsert({
      where: { url: articleUrl },
      update: {},
      create: {
        title: ev.title,
        url: articleUrl,
        sourceId: source.id,
        publishedAt: new Date(ev.date),
        summary: ev.summary,
        language: "en",
        country: ev.country,
      },
    });

    // For PRODUCTIVITY_GAIN events, jobs are 0
    const event = await prisma.event.create({
      data: {
        eventType: ev.eventType,
        companyId: company.id,
        companyName: ev.company,
        country: ev.country,
        industry: ev.industry,
        dateAnnounced: new Date(ev.date),
        jobsCutAnnounced: 0,
        conservativeAiJobs: 0,
        weightedAiJobs: 0,
        upperAiJobs: 0,
        attributionCategory: ev.category,
        attributionWeight: coreWeights[ev.category],
        confidenceScore: ev.category === "EXPLICIT" ? 0.95 : ev.category === "STRONG" ? 0.8 : 0.6,
        publicSummary: ev.summary,
        reviewStatus: "PROVISIONAL",
        reviewLevel: "AUTOMATED",
        needsReview: true,
      },
    });

    // Link article to event
    await prisma.articleEvent.create({
      data: {
        articleId: article.id,
        eventId: event.id,
        isPrimary: true,
      },
    });

    eventsCreated++;
    console.log(`[EVENT ${eventsCreated}] ${ev.company}: ${ev.title.substring(0, 70)}`);
  }

  // ===== INSERT PRODUCTIVITY CLAIMS =====
  for (const cl of claims) {
    const existing = await prisma.productivityClaim.findFirst({
      where: {
        companyName: cl.companyName,
        claim: { contains: cl.claim.substring(0, 50) },
      },
    });

    if (existing) {
      console.log(`[SKIP CLAIM] ${cl.companyName}: already exists`);
      claimsSkipped++;
      continue;
    }

    await prisma.productivityClaim.create({
      data: {
        companyName: cl.companyName,
        country: cl.country,
        industry: cl.industry,
        claim: cl.claim,
        claimType: cl.claimType,
        estimatedImpact: cl.estimatedImpact,
        confidence: cl.confidence,
        sourceUrl: cl.sourceUrl,
        publishedAt: new Date(cl.publishedAt),
        reviewStatus: "PROVISIONAL",
      },
    });

    claimsCreated++;
    console.log(`[CLAIM ${claimsCreated}] ${cl.companyName}: ${cl.claimType}`);
  }

  console.log(`\nDone.`);
  console.log(`Events: created ${eventsCreated}, skipped ${eventsSkipped}`);
  console.log(`Claims: created ${claimsCreated}, skipped ${claimsSkipped}`);
  await prisma.$disconnect();
  await pool.end();
}

main().catch((e) => {
  console.error(e);
  process.exit(1);
});
