export interface SourceSeed {
  name: string;
  url: string;
  type: string;
  category: string;
  region?: string;
  country?: string;
  language?: string;
  description?: string;
  tier: number;
  checkFrequency?: string;
  hasApi?: boolean;
  hasRss?: boolean;
  rssUrl?: string;
  paywalled?: boolean;
}

export const warnStateSources: SourceSeed[] = [
  // ============================================================
  // All 50 States + DC — WARN Databases
  // ============================================================
  {
    name: 'Alabama WARN Database',
    url: 'https://labor.alabama.gov/',
    type: 'government',
    category: 'both',
    region: 'US',
    country: 'US',
    language: 'en',
    description: 'Alabama Dept. of Labor. No public WARN database found; contact agency directly.',
    tier: 5,
    checkFrequency: 'weekly',
  },
  {
    name: 'Alaska WARN Database',
    url: 'https://jobs.state.ak.us/RR/WARN_notices.htm',
    type: 'government',
    category: 'both',
    region: 'US',
    country: 'US',
    language: 'en',
    description: 'Alaska Dept. of Labor & Workforce Development WARN notices list.',
    tier: 5,
    checkFrequency: 'weekly',
  },
  {
    name: 'Arizona WARN Database',
    url: 'https://www.azjobconnection.gov/warn_info',
    type: 'government',
    category: 'both',
    region: 'US',
    country: 'US',
    language: 'en',
    description: 'Arizona Dept. of Economic Security / ARIZONA@WORK searchable WARN list.',
    tier: 5,
    checkFrequency: 'weekly',
  },
  {
    name: 'Arkansas WARN Database',
    url: 'https://dws.arkansas.gov/workforce-services/employers/dislocated-worker-services/',
    type: 'government',
    category: 'both',
    region: 'US',
    country: 'US',
    language: 'en',
    description: 'Arkansas Div. of Workforce Services Rapid Response page; contact for WARN data.',
    tier: 5,
    checkFrequency: 'weekly',
  },
  {
    name: 'California WARN Database',
    url: 'https://edd.ca.gov/en/jobs_and_training/Layoff_Services_WARN/',
    type: 'government',
    category: 'both',
    region: 'US',
    country: 'US',
    language: 'en',
    description:
      'California EDD extensive WARN database. PDFs by year, searchable by company/location. State mini-WARN (75+ employees).',
    tier: 5,
    checkFrequency: 'weekly',
  },
  {
    name: 'Colorado WARN Database',
    url: 'https://cdle.colorado.gov/employers/layoff-separations/layoff-warn-list',
    type: 'government',
    category: 'both',
    region: 'US',
    country: 'US',
    language: 'en',
    description: 'Colorado Dept. of Labor & Employment downloadable WARN listings.',
    tier: 5,
    checkFrequency: 'weekly',
  },
  {
    name: 'Connecticut WARN Database',
    url: 'https://www.ctdol.state.ct.us/progsupt/bussrvce/warnreports/warnreports.htm',
    type: 'government',
    category: 'both',
    region: 'US',
    country: 'US',
    language: 'en',
    description:
      'Connecticut Dept. of Labor monthly WARN reports, annual listings. State mini-WARN.',
    tier: 5,
    checkFrequency: 'weekly',
  },
  {
    name: 'Delaware WARN Database',
    url: 'https://joblink.delaware.gov/search/warn_lookups/new',
    type: 'government',
    category: 'both',
    region: 'US',
    country: 'US',
    language: 'en',
    description: 'Delaware JobLink searchable WARN database. State mini-WARN enacted.',
    tier: 5,
    checkFrequency: 'weekly',
  },
  {
    name: 'Florida WARN Database',
    url: 'https://floridajobs.org/office-directory/division-of-workforce-services/workforce-programs/reemployment-and-emergency-assistance-coordination-team-react/warn-notices',
    type: 'government',
    category: 'both',
    region: 'US',
    country: 'US',
    language: 'en',
    description: 'Florida Dept. of Economic Opportunity WARN notices via REACT team.',
    tier: 5,
    checkFrequency: 'weekly',
  },
  {
    name: 'Georgia WARN Database',
    url: 'https://www.tcsg.edu/warn/',
    type: 'government',
    category: 'both',
    region: 'US',
    country: 'US',
    language: 'en',
    description: 'Georgia Technical College System (TCSG) layoff & closure notification.',
    tier: 5,
    checkFrequency: 'weekly',
  },
  {
    name: 'Hawaii WARN Database',
    url: 'https://labor.hawaii.gov/wdc/the-warn-act/',
    type: 'government',
    category: 'both',
    region: 'US',
    country: 'US',
    language: 'en',
    description:
      'Hawaii Dept. of Labor & Industrial Relations Workforce Development Council. State mini-WARN with extended notice + severance obligations.',
    tier: 5,
    checkFrequency: 'weekly',
  },
  {
    name: 'Idaho WARN Database',
    url: 'https://labor.idaho.gov/dnn/Businesses/Layoff-Assistance',
    type: 'government',
    category: 'both',
    region: 'US',
    country: 'US',
    language: 'en',
    description: 'Idaho Dept. of Labor layoff assistance page with WARN info.',
    tier: 5,
    checkFrequency: 'weekly',
  },
  {
    name: 'Illinois WARN Database',
    url: 'https://dceo.illinois.gov/workforcedevelopment/warn.html',
    type: 'government',
    category: 'both',
    region: 'US',
    country: 'US',
    language: 'en',
    description:
      'Illinois Dept. of Commerce & Economic Opportunity searchable WARN notices. State mini-WARN.',
    tier: 5,
    checkFrequency: 'weekly',
  },
  {
    name: 'Indiana WARN Database',
    url: 'https://www.in.gov/dwd/warn-notices/',
    type: 'government',
    category: 'both',
    region: 'US',
    country: 'US',
    language: 'en',
    description: 'Indiana Dept. of Workforce Development WARN notices list.',
    tier: 5,
    checkFrequency: 'weekly',
  },
  {
    name: 'Iowa WARN Database',
    url: 'https://workforce.iowa.gov/employers/resources/warn',
    type: 'government',
    category: 'both',
    region: 'US',
    country: 'US',
    language: 'en',
    description:
      'Iowa Workforce Development WARN info and notices. State mini-WARN (30-day notice, state-specific rules).',
    tier: 5,
    checkFrequency: 'weekly',
  },
  {
    name: 'Kansas WARN Database',
    url: 'https://www.kansascommerce.gov/',
    type: 'government',
    category: 'both',
    region: 'US',
    country: 'US',
    language: 'en',
    description:
      'Kansas Dept. of Commerce; contact Workforce Services division. State mini-WARN.',
    tier: 5,
    checkFrequency: 'weekly',
  },
  {
    name: 'Kentucky WARN Database',
    url: 'https://kcc.ky.gov/employer/Pages/Business-Downsizing-Assistance---WARN.aspx',
    type: 'government',
    category: 'both',
    region: 'US',
    country: 'US',
    language: 'en',
    description: 'Kentucky Career Center WARN notices by year.',
    tier: 5,
    checkFrequency: 'weekly',
  },
  {
    name: 'Louisiana WARN Database',
    url: 'https://www.laworks.net/WorkforceDev/WFD_WARNSampleLetter.asp',
    type: 'government',
    category: 'both',
    region: 'US',
    country: 'US',
    language: 'en',
    description: 'Louisiana Workforce Commission WARN contact/submission info. No state mini-WARN.',
    tier: 5,
    checkFrequency: 'weekly',
  },
  {
    name: 'Maine WARN Database',
    url: 'https://www.maine.gov/labor/',
    type: 'government',
    category: 'both',
    region: 'US',
    country: 'US',
    language: 'en',
    description:
      'Maine Dept. of Labor. State mini-WARN (90-day notice requirement + severance).',
    tier: 5,
    checkFrequency: 'weekly',
  },
  {
    name: 'Maryland WARN Database',
    url: 'https://labor.maryland.gov/employment/warn.shtml',
    type: 'government',
    category: 'both',
    region: 'US',
    country: 'US',
    language: 'en',
    description:
      'Maryland Div. of Workforce Dev. & Adult Learning WARN notices. State requires 60-day notice for relocations/closings.',
    tier: 5,
    checkFrequency: 'weekly',
  },
  {
    name: 'Massachusetts WARN Database',
    url: 'https://www.mass.gov/info-details/worker-adjustment-and-retraining-notification-act-warn',
    type: 'government',
    category: 'both',
    region: 'US',
    country: 'US',
    language: 'en',
    description:
      'Massachusetts Executive Office of Labor & Workforce Development WARN info. State mini-WARN.',
    tier: 5,
    checkFrequency: 'weekly',
  },
  {
    name: 'Michigan WARN Database',
    url: 'https://www.michigan.gov/leo/bureaus-agencies/wd/data-public-notices/warn-notices',
    type: 'government',
    category: 'both',
    region: 'US',
    country: 'US',
    language: 'en',
    description:
      'Michigan Labor & Economic Opportunity (LEO) public WARN notices. State mini-WARN.',
    tier: 5,
    checkFrequency: 'weekly',
  },
  {
    name: 'Minnesota WARN Database',
    url: 'https://mn.gov/deed/warn/',
    type: 'government',
    category: 'both',
    region: 'US',
    country: 'US',
    language: 'en',
    description:
      'Minnesota DEED WARN database. State mini-WARN (50+ employees, broader than federal).',
    tier: 5,
    checkFrequency: 'weekly',
  },
  {
    name: 'Mississippi WARN Database',
    url: 'https://mdes.ms.gov/information-center/warn-information/',
    type: 'government',
    category: 'both',
    region: 'US',
    country: 'US',
    language: 'en',
    description: 'Mississippi Dept. of Employment Security WARN information page.',
    tier: 5,
    checkFrequency: 'weekly',
  },
  {
    name: 'Missouri WARN Database',
    url: 'https://jobs.mo.gov/employer/warn',
    type: 'government',
    category: 'both',
    region: 'US',
    country: 'US',
    language: 'en',
    description: 'Missouri Office of Workforce Development WARN notices. Annual reports by year.',
    tier: 5,
    checkFrequency: 'weekly',
  },
  {
    name: 'Montana WARN Database',
    url: 'https://wsd.dli.mt.gov/wioa/related-links/warn-notice-page',
    type: 'government',
    category: 'both',
    region: 'US',
    country: 'US',
    language: 'en',
    description:
      'Montana Dept. of Labor & Industry WARN notice page. State law applies only to government facilities.',
    tier: 5,
    checkFrequency: 'weekly',
  },
  {
    name: 'Nebraska WARN Database',
    url: 'https://dol.nebraska.gov/ReemploymentServices/LayoffServices/LayoffsAndDownsizingWARN',
    type: 'government',
    category: 'both',
    region: 'US',
    country: 'US',
    language: 'en',
    description: 'Nebraska Dept. of Labor WARN listing.',
    tier: 5,
    checkFrequency: 'weekly',
  },
  {
    name: 'Nevada WARN Database',
    url: 'https://detr.nv.gov/',
    type: 'government',
    category: 'both',
    region: 'US',
    country: 'US',
    language: 'en',
    description:
      'Nevada Dept. of Employment, Training & Rehabilitation. Contact DETR for WARN data.',
    tier: 5,
    checkFrequency: 'weekly',
  },
  {
    name: 'New Hampshire WARN Database',
    url: 'https://www.nhes.nh.gov/services/employers/compliance.htm',
    type: 'government',
    category: 'both',
    region: 'US',
    country: 'US',
    language: 'en',
    description:
      'New Hampshire Employment Security. State mini-WARN: must report layoffs of 25+ individuals.',
    tier: 5,
    checkFrequency: 'weekly',
  },
  {
    name: 'New Jersey WARN Database',
    url: 'https://www.nj.gov/labor/',
    type: 'government',
    category: 'both',
    region: 'US',
    country: 'US',
    language: 'en',
    description:
      'New Jersey Dept. of Labor & Workforce Development. State mini-WARN (90-day notice, 50+ employees). Contact for WARN list.',
    tier: 5,
    checkFrequency: 'weekly',
  },
  {
    name: 'New Mexico WARN Database',
    url: 'https://www.dws.state.nm.us/',
    type: 'government',
    category: 'both',
    region: 'US',
    country: 'US',
    language: 'en',
    description:
      'New Mexico Dept. of Workforce Solutions. No state mini-WARN. Contact Rapid Response.',
    tier: 5,
    checkFrequency: 'weekly',
  },
  {
    name: 'New York WARN Database',
    url: 'https://dol.ny.gov/warn-dashboard',
    type: 'government',
    category: 'both',
    region: 'US',
    country: 'US',
    language: 'en',
    description:
      'New York Dept. of Labor interactive WARN dashboard. Filter by county, industry, date. State mini-WARN (90-day notice, 50+ employees).',
    tier: 5,
    checkFrequency: 'weekly',
  },
  {
    name: 'North Carolina WARN Database',
    url: 'https://www.commerce.nc.gov/data-tools-reports/labor-market-data-tools/workforce-warn-reports',
    type: 'government',
    category: 'both',
    region: 'US',
    country: 'US',
    language: 'en',
    description: 'North Carolina Dept. of Commerce WARN reports.',
    tier: 5,
    checkFrequency: 'weekly',
  },
  {
    name: 'North Dakota WARN Database',
    url: 'https://www.jobsnd.com/unemployment-business-tax/employers-guide/employer-responsibilities-employee-separations',
    type: 'government',
    category: 'both',
    region: 'US',
    country: 'US',
    language: 'en',
    description:
      'Job Service North Dakota. State law: 48-hour notice for mass separation (25+ workers).',
    tier: 5,
    checkFrequency: 'weekly',
  },
  {
    name: 'Ohio WARN Database',
    url: 'https://jfs.ohio.gov/',
    type: 'government',
    category: 'both',
    region: 'US',
    country: 'US',
    language: 'en',
    description: 'Ohio Dept. of Job & Family Services WARN notices (1996-present). Individual PDFs.',
    tier: 5,
    checkFrequency: 'weekly',
  },
  {
    name: 'Oklahoma WARN Database',
    url: 'https://www.employoklahoma.gov/Participants/s/warnnotices',
    type: 'government',
    category: 'both',
    region: 'US',
    country: 'US',
    language: 'en',
    description: 'Oklahoma Works WARN layoff notices list.',
    tier: 5,
    checkFrequency: 'weekly',
  },
  {
    name: 'Oregon WARN Database',
    url: 'https://www.oregon.gov/highered/about/workforce/pages/warn.aspx',
    type: 'government',
    category: 'both',
    region: 'US',
    country: 'US',
    language: 'en',
    description:
      'Oregon Higher Education Coordinating Commission WARN Act Notifications. State mini-WARN.',
    tier: 5,
    checkFrequency: 'weekly',
  },
  {
    name: 'Pennsylvania WARN Database',
    url: 'https://www.dli.pa.gov/Individuals/Workforce-Development/warn/Pages/default.aspx',
    type: 'government',
    category: 'both',
    region: 'US',
    country: 'US',
    language: 'en',
    description: 'Pennsylvania Dept. of Labor & Industry WARN notices.',
    tier: 5,
    checkFrequency: 'weekly',
  },
  {
    name: 'Rhode Island WARN Database',
    url: 'https://dlt.ri.gov/employers/worker-adjustment-and-retraining-notification-warn',
    type: 'government',
    category: 'both',
    region: 'US',
    country: 'US',
    language: 'en',
    description: 'Rhode Island Dept. of Labor & Training WARN info and notices. State mini-WARN.',
    tier: 5,
    checkFrequency: 'weekly',
  },
  {
    name: 'South Carolina WARN Database',
    url: 'https://scworks.org/employer/employer-programs/worker-adjustment-and-retraining-notification-warn-act',
    type: 'government',
    category: 'both',
    region: 'US',
    country: 'US',
    language: 'en',
    description: 'South Carolina SC Works WARN info. State mini-WARN.',
    tier: 5,
    checkFrequency: 'weekly',
  },
  {
    name: 'South Dakota WARN Database',
    url: 'https://dlr.sd.gov/workforce_services/businesses/warn_notices.aspx',
    type: 'government',
    category: 'both',
    region: 'US',
    country: 'US',
    language: 'en',
    description: 'South Dakota Dept. of Labor & Regulation WARN notices. No state mini-WARN.',
    tier: 5,
    checkFrequency: 'weekly',
  },
  {
    name: 'Tennessee WARN Database',
    url: 'https://www.tn.gov/workforce/employers/staffing-redirect/layoffs---unemployment/warn-notices.html',
    type: 'government',
    category: 'both',
    region: 'US',
    country: 'US',
    language: 'en',
    description:
      'Tennessee Dept. of Labor & Workforce Development WARN notices. State mini-WARN (50-99 employees covered).',
    tier: 5,
    checkFrequency: 'weekly',
  },
  {
    name: 'Texas WARN Database',
    url: 'https://www.twc.texas.gov/data-reports/warn-notice',
    type: 'government',
    category: 'both',
    region: 'US',
    country: 'US',
    language: 'en',
    description: 'Texas Workforce Commission WARN data in Excel format. Plant closures and layoff notices.',
    tier: 5,
    checkFrequency: 'weekly',
  },
  {
    name: 'Utah WARN Database',
    url: 'https://jobs.utah.gov/employer/business/warnnotices.html',
    type: 'government',
    category: 'both',
    region: 'US',
    country: 'US',
    language: 'en',
    description: 'Utah Dept. of Workforce Services WARN notices.',
    tier: 5,
    checkFrequency: 'weekly',
  },
  {
    name: 'Vermont WARN Database',
    url: 'https://labor.vermont.gov/',
    type: 'government',
    category: 'both',
    region: 'US',
    country: 'US',
    language: 'en',
    description:
      'Vermont Dept. of Labor. State mini-WARN: Notice of Potential Layoffs Act (NPLA) + Mass Separation Notification rule.',
    tier: 5,
    checkFrequency: 'weekly',
  },
  {
    name: 'Virginia WARN Database',
    url: 'https://www.vec.virginia.gov/warn-notices',
    type: 'government',
    category: 'both',
    region: 'US',
    country: 'US',
    language: 'en',
    description: 'Virginia Employment Commission WARN notices.',
    tier: 5,
    checkFrequency: 'weekly',
  },
  {
    name: 'Washington WARN Database',
    url: 'https://esd.wa.gov/employer-requirements/layoffs-and-employee-notifications/worker-adjustment-and-retraining-notification-warn-layoff-and-closure-database',
    type: 'government',
    category: 'both',
    region: 'US',
    country: 'US',
    language: 'en',
    description: 'Washington Employment Security Department full searchable WARN database.',
    tier: 5,
    checkFrequency: 'weekly',
  },
  {
    name: 'West Virginia WARN Database',
    url: 'https://workforcewv.org/public-information/warn-notices',
    type: 'government',
    category: 'both',
    region: 'US',
    country: 'US',
    language: 'en',
    description: 'WorkForce West Virginia WARN listing.',
    tier: 5,
    checkFrequency: 'weekly',
  },
  {
    name: 'Wisconsin WARN Database',
    url: 'https://dwd.wisconsin.gov/dislocatedworker/warn/',
    type: 'government',
    category: 'both',
    region: 'US',
    country: 'US',
    language: 'en',
    description:
      'Wisconsin Dept. of Workforce Development layoff notices filed by year. State mini-WARN.',
    tier: 5,
    checkFrequency: 'weekly',
  },
  {
    name: 'Wyoming WARN Database',
    url: 'https://www.wyoming.gov/agencies/workforce-services/',
    type: 'government',
    category: 'both',
    region: 'US',
    country: 'US',
    language: 'en',
    description:
      'Wyoming Dept. of Workforce Services. No state mini-WARN. Contact agency for WARN data.',
    tier: 5,
    checkFrequency: 'weekly',
  },
  {
    name: 'District of Columbia WARN Database',
    url: 'https://does.dc.gov/',
    type: 'government',
    category: 'both',
    region: 'US',
    country: 'US',
    language: 'en',
    description: 'DC Dept. of Employment Services (DOES). Contact DOES for WARN data.',
    tier: 5,
    checkFrequency: 'weekly',
  },

  // ============================================================
  // US Territories
  // ============================================================
  {
    name: 'Puerto Rico WARN Database',
    url: 'https://www.trabajo.pr.gov/',
    type: 'government',
    category: 'both',
    region: 'US',
    country: 'US',
    language: 'es',
    description:
      'Puerto Rico Dept. of Labor & Human Resources (DTRH). Covered under federal WARN (20 CFR Part 639). Has Unjust Dismissal Act for group layoffs. No state mini-WARN.',
    tier: 5,
    checkFrequency: 'weekly',
  },
  {
    name: 'US Virgin Islands WARN Database',
    url: 'https://www.vidol.gov/',
    type: 'government',
    category: 'both',
    region: 'US',
    country: 'US',
    language: 'en',
    description:
      'USVI Dept. of Labor. Explicitly covered under federal WARN Act (20 CFR Part 639).',
    tier: 5,
    checkFrequency: 'weekly',
  },
  {
    name: 'Guam WARN Database',
    url: 'https://dol.guam.gov/',
    type: 'government',
    category: 'both',
    region: 'US',
    country: 'US',
    language: 'en',
    description: 'Guam Dept. of Labor. Subject to federal WARN as US territory.',
    tier: 5,
    checkFrequency: 'weekly',
  },
  {
    name: 'American Samoa WARN Database',
    url: 'https://www.americansamoa.gov/',
    type: 'government',
    category: 'both',
    region: 'US',
    country: 'US',
    language: 'en',
    description:
      'American Samoa Dept. of Human Resources. Small employer base; federal WARN applies.',
    tier: 5,
    checkFrequency: 'weekly',
  },
  {
    name: 'Northern Mariana Islands WARN Database',
    url: 'https://www.marianaslabor.net/',
    type: 'government',
    category: 'both',
    region: 'US',
    country: 'US',
    language: 'en',
    description: 'CNMI Dept. of Labor. Federal WARN applies.',
    tier: 5,
    checkFrequency: 'weekly',
  },

  // ============================================================
  // Multi-State Aggregators (excluding WARN Firehose and LayoffData)
  // ============================================================
  {
    name: 'WARNTracker',
    url: 'https://www.warntracker.com/',
    type: 'aggregator',
    category: 'both',
    region: 'US',
    country: 'US',
    language: 'en',
    description:
      'Live layoffs from public WARN records. Filter by state, year (back to 1990).',
    tier: 4,
    checkFrequency: 'daily',
  },
  {
    name: 'warn-scraper (Stanford/Big Local News)',
    url: 'https://github.com/biglocalnews/warn-scraper',
    type: 'aggregator',
    category: 'both',
    region: 'US',
    country: 'US',
    language: 'en',
    description:
      'Python CLI scraper for all state WARN sites. Open source, automated via GitHub Actions.',
    tier: 4,
    checkFrequency: 'daily',
  },
  {
    name: 'WARNActNews',
    url: 'https://www.warnactnews.com/',
    type: 'aggregator',
    category: 'both',
    region: 'US',
    country: 'US',
    language: 'en',
    description: 'State-specific WARN pages, news coverage.',
    tier: 4,
    checkFrequency: 'daily',
  },
  {
    name: '0xdade WARN URL Gist',
    url: 'https://gist.github.com/0xdade/c90d11a7f2d2591ad0a980b9c7ed232f',
    type: 'aggregator',
    category: 'both',
    region: 'US',
    country: 'US',
    language: 'en',
    description: 'Aggregation of state WARN URLs (work in progress).',
    tier: 4,
    checkFrequency: 'monthly',
  },

  // ============================================================
  // Federal Sources — Department of Labor
  // ============================================================
  {
    name: 'DOL WARN Act Compliance (ETA)',
    url: 'https://www.dol.gov/agencies/eta/layoffs/warn',
    type: 'government',
    category: 'both',
    region: 'US',
    country: 'US',
    language: 'en',
    description: 'Federal WARN overview, links to state contacts.',
    tier: 4,
    checkFrequency: 'monthly',
  },
  {
    name: 'DOL Plant Closings & Layoffs',
    url: 'https://www.dol.gov/general/topic/termination/plantclosings',
    type: 'government',
    category: 'both',
    region: 'US',
    country: 'US',
    language: 'en',
    description: 'General DOL resource page on plant closings and layoffs.',
    tier: 4,
    checkFrequency: 'monthly',
  },
  {
    name: 'DOL Rapid Response Services (ETA)',
    url: 'https://www.dol.gov/agencies/eta/layoffs',
    type: 'government',
    category: 'both',
    region: 'US',
    country: 'US',
    language: 'en',
    description: 'Employer layoff notification coordination.',
    tier: 4,
    checkFrequency: 'monthly',
  },
  {
    name: 'DOL State Dislocated Worker Contacts',
    url: 'https://www.dol.gov/agencies/eta/layoffs/contact',
    type: 'government',
    category: 'both',
    region: 'US',
    country: 'US',
    language: 'en',
    description: 'Directory of state rapid response contacts.',
    tier: 4,
    checkFrequency: 'monthly',
  },
  {
    name: 'DOL UI Data Dashboard',
    url: 'https://oui.doleta.gov/unemploy/DataDashboard.asp',
    type: 'government',
    category: 'both',
    region: 'US',
    country: 'US',
    language: 'en',
    description: 'Unemployment insurance claims data dashboard.',
    tier: 4,
    checkFrequency: 'weekly',
  },
  {
    name: 'DOL Trade Adjustment Assistance (TAA)',
    url: 'https://www.dol.gov/agencies/eta/tradeact',
    type: 'government',
    category: 'both',
    region: 'US',
    country: 'US',
    language: 'en',
    description: 'Trade-related layoff petitions and certifications.',
    tier: 4,
    checkFrequency: 'weekly',
  },
  {
    name: 'DOL State Labor Offices Directory',
    url: 'https://www.dol.gov/agencies/whd/state/contacts',
    type: 'government',
    category: 'both',
    region: 'US',
    country: 'US',
    language: 'en',
    description: 'All state labor department contacts.',
    tier: 4,
    checkFrequency: 'monthly',
  },

  // ============================================================
  // Bureau of Labor Statistics (BLS) — specific datasets
  // (skipping BLS main / BLS Data API as tier 1-3 already seeded)
  // ============================================================
  {
    name: 'BLS JOLTS (Job Openings & Labor Turnover)',
    url: 'https://www.bls.gov/jlt/',
    type: 'government',
    category: 'both',
    region: 'US',
    country: 'US',
    language: 'en',
    description:
      'Monthly layoffs/discharges, hires, separations data. State-level estimates available.',
    tier: 4,
    checkFrequency: 'monthly',
    hasApi: true,
  },
  {
    name: 'BLS JOLTS State Estimates',
    url: 'https://www.bls.gov/jlt/jlt_statedata_background.htm',
    type: 'government',
    category: 'both',
    region: 'US',
    country: 'US',
    language: 'en',
    description: 'State-by-state JOLTS breakdowns.',
    tier: 4,
    checkFrequency: 'monthly',
  },
  {
    name: 'BLS Current Employment Statistics (CES)',
    url: 'https://www.bls.gov/ces/',
    type: 'government',
    category: 'both',
    region: 'US',
    country: 'US',
    language: 'en',
    description: 'Monthly payroll employment by industry.',
    tier: 4,
    checkFrequency: 'monthly',
    hasApi: true,
  },
  {
    name: 'BLS QCEW (Quarterly Census of Employment & Wages)',
    url: 'https://www.bls.gov/cew/',
    type: 'government',
    category: 'both',
    region: 'US',
    country: 'US',
    language: 'en',
    description:
      'Establishment-level employment/wages from UI records. 95%+ coverage.',
    tier: 4,
    checkFrequency: 'quarterly',
    hasApi: true,
  },
  {
    name: 'BLS Data API',
    url: 'https://www.bls.gov/bls/api_features.htm',
    type: 'government',
    category: 'both',
    region: 'US',
    country: 'US',
    language: 'en',
    description: 'Programmatic access to all BLS series. Free tier available.',
    tier: 4,
    checkFrequency: 'monthly',
    hasApi: true,
  },
  {
    name: 'BLS Employment Situation Summary',
    url: 'https://www.bls.gov/news.release/empsit.nr0.htm',
    type: 'government',
    category: 'both',
    region: 'US',
    country: 'US',
    language: 'en',
    description: 'Monthly jobs report (Employment Situation).',
    tier: 4,
    checkFrequency: 'monthly',
  },
  {
    name: 'BLS Occupational Employment & Wage Statistics (OES)',
    url: 'https://www.bls.gov/oes/',
    type: 'government',
    category: 'both',
    region: 'US',
    country: 'US',
    language: 'en',
    description:
      'Employment by occupation — useful for tracking AI-affected roles.',
    tier: 4,
    checkFrequency: 'quarterly',
    hasApi: true,
  },
  {
    name: 'BLS State Labor Market Contacts',
    url: 'https://www.bls.gov/bls/ofolist.htm',
    type: 'government',
    category: 'both',
    region: 'US',
    country: 'US',
    language: 'en',
    description: 'State LMI office directory.',
    tier: 4,
    checkFrequency: 'monthly',
  },

  // ============================================================
  // Federal Reserve Economic Data (FRED) — specific series
  // (skipping FRED main as tier 1-3 already seeded)
  // ============================================================
  {
    name: 'FRED Layoffs + BLS Series',
    url: 'https://fred.stlouisfed.org/tags/series?t=bls%3Blayoffs',
    type: 'government',
    category: 'both',
    region: 'US',
    country: 'US',
    language: 'en',
    description: '82 FRED series tagged layoffs+BLS.',
    tier: 4,
    checkFrequency: 'monthly',
    hasApi: true,
  },
  {
    name: 'FRED Employment + BLS Series',
    url: 'https://fred.stlouisfed.org/tags/series?t=bls%3Bemployment',
    type: 'government',
    category: 'both',
    region: 'US',
    country: 'US',
    language: 'en',
    description: '88,000+ employment data series from BLS via FRED.',
    tier: 4,
    checkFrequency: 'monthly',
    hasApi: true,
  },
  {
    name: 'FRED Unemployment + BLS Series',
    url: 'https://fred.stlouisfed.org/tags/series?t=bls%3Bunemployment',
    type: 'government',
    category: 'both',
    region: 'US',
    country: 'US',
    language: 'en',
    description: '17,821 unemployment series from BLS via FRED.',
    tier: 4,
    checkFrequency: 'monthly',
    hasApi: true,
  },
  {
    name: 'FRED All BLS Series',
    url: 'https://fred.stlouisfed.org/tags/series?t=bls',
    type: 'government',
    category: 'both',
    region: 'US',
    country: 'US',
    language: 'en',
    description: '180,000+ BLS-sourced series via FRED.',
    tier: 4,
    checkFrequency: 'monthly',
    hasApi: true,
  },
  {
    name: 'FRED API',
    url: 'https://fred.stlouisfed.org/docs/api/fred/',
    type: 'government',
    category: 'both',
    region: 'US',
    country: 'US',
    language: 'en',
    description: 'FRED API with free key. Excellent documentation.',
    tier: 4,
    checkFrequency: 'monthly',
    hasApi: true,
  },
  {
    name: 'FRED Blog',
    url: 'https://fredblog.stlouisfed.org/',
    type: 'government',
    category: 'both',
    region: 'US',
    country: 'US',
    language: 'en',
    description: 'FRED analysis and data visualization articles.',
    tier: 4,
    checkFrequency: 'weekly',
  },

  // ============================================================
  // Census Bureau
  // ============================================================
  {
    name: 'Census Employment Data Hub',
    url: 'https://www.census.gov/topics/employment/data.html',
    type: 'government',
    category: 'both',
    region: 'US',
    country: 'US',
    language: 'en',
    description: 'Census Bureau central employment data page.',
    tier: 4,
    checkFrequency: 'quarterly',
  },
  {
    name: 'Census American Community Survey (ACS)',
    url: 'https://www.census.gov/programs-surveys/acs.html',
    type: 'government',
    category: 'both',
    region: 'US',
    country: 'US',
    language: 'en',
    description:
      'Detailed employment, income, occupation data. 5-year estimates.',
    tier: 4,
    checkFrequency: 'quarterly',
    hasApi: true,
  },
  {
    name: 'Census EEO Tabulation',
    url: 'https://www.census.gov/acs/www/data/eeo-data/',
    type: 'government',
    category: 'both',
    region: 'US',
    country: 'US',
    language: 'en',
    description:
      'Employment by race/ethnicity/sex/occupation from ACS.',
    tier: 4,
    checkFrequency: 'quarterly',
  },
  {
    name: 'Census Equal Employment Opportunity Data',
    url: 'https://www.census.gov/topics/employment/equal-employment-opportunity-tabulation.html',
    type: 'government',
    category: 'both',
    region: 'US',
    country: 'US',
    language: 'en',
    description: 'Workforce composition benchmarks.',
    tier: 4,
    checkFrequency: 'quarterly',
  },
  {
    name: 'Census Opportunity Project (Workforce)',
    url: 'https://opportunity.census.gov/data/workforce/',
    type: 'government',
    category: 'both',
    region: 'US',
    country: 'US',
    language: 'en',
    description: 'Workforce-related open datasets from Census.',
    tier: 4,
    checkFrequency: 'quarterly',
  },

  // ============================================================
  // EEOC
  // ============================================================
  {
    name: 'EEOC Data & Statistics',
    url: 'https://www.eeoc.gov/data/data-and-statistics',
    type: 'government',
    category: 'both',
    region: 'US',
    country: 'US',
    language: 'en',
    description:
      'Charge statistics, litigation data, employer EEO-1 reports.',
    tier: 4,
    checkFrequency: 'quarterly',
  },
  {
    name: 'EEOC EEO-1 Component 1 Data',
    url: 'https://www.eeoc.gov/data/eeo-1-data',
    type: 'government',
    category: 'both',
    region: 'US',
    country: 'US',
    language: 'en',
    description:
      'Employer workforce demographic reports (companies 100+ employees).',
    tier: 4,
    checkFrequency: 'quarterly',
  },

  // ============================================================
  // SEC EDGAR — specific variants (skipping main EDGAR as already seeded)
  // ============================================================
  {
    name: 'SEC EDGAR Full-Text Search (Workforce Reduction)',
    url: 'https://efts.sec.gov/LATEST/search-index?q=%22workforce+reduction%22&dateRange=custom',
    type: 'government',
    category: 'both',
    region: 'US',
    country: 'US',
    language: 'en',
    description:
      'Search 8-K filings for "workforce reduction", "layoff", "restructuring".',
    tier: 4,
    checkFrequency: 'daily',
    hasApi: true,
  },
  {
    name: 'SEC EDGAR Company Search',
    url: 'https://www.sec.gov/cgi-bin/browse-edgar?action=getcompany',
    type: 'government',
    category: 'both',
    region: 'US',
    country: 'US',
    language: 'en',
    description: 'Look up specific company filings on EDGAR.',
    tier: 4,
    checkFrequency: 'daily',
    hasApi: true,
  },
  {
    name: 'SEC EDGAR 8-K Current Reports',
    url: 'https://www.sec.gov/cgi-bin/browse-edgar?type=8-K&action=getcompany',
    type: 'government',
    category: 'both',
    region: 'US',
    country: 'US',
    language: 'en',
    description:
      '8-K filings often disclose layoffs under Item 2.05 (Costs of Exit/Disposal) or Item 8.01 (Other Events).',
    tier: 4,
    checkFrequency: 'daily',
    hasApi: true,
  },
  {
    name: 'Fed Reserve Working Paper — Tracking Layoffs with SEC Filings',
    url: 'https://www.federalreserve.gov/econres/feds/files/2024020pap.pdf',
    type: 'government',
    category: 'both',
    region: 'US',
    country: 'US',
    language: 'en',
    description:
      '"Tracking Real Time Layoffs with SEC Filings" — methodology for extracting layoff data from 8-Ks.',
    tier: 4,
    checkFrequency: 'monthly',
  },

  // ============================================================
  // GAO
  // ============================================================
  {
    name: 'GAO Reports & Testimonies',
    url: 'https://www.gao.gov/reports-testimonies',
    type: 'government',
    category: 'both',
    region: 'US',
    country: 'US',
    language: 'en',
    description:
      'Search for workforce, technology displacement, AI impact reports.',
    tier: 4,
    checkFrequency: 'monthly',
  },
  {
    name: 'GAO Women in the Workforce',
    url: 'https://www.gao.gov/assets/gao-23-106320.pdf',
    type: 'government',
    category: 'both',
    region: 'US',
    country: 'US',
    language: 'en',
    description: 'Workforce demographic analysis report.',
    tier: 4,
    checkFrequency: 'monthly',
  },
  {
    name: 'GAO Federal Workforce Demographics',
    url: 'https://www.gao.gov/assets/d24105924.pdf',
    type: 'government',
    category: 'both',
    region: 'US',
    country: 'US',
    language: 'en',
    description: 'Federal workforce data analysis using ACS.',
    tier: 4,
    checkFrequency: 'monthly',
  },

  // ============================================================
  // SBA
  // ============================================================
  {
    name: 'SBA Main',
    url: 'https://www.sba.gov/',
    type: 'government',
    category: 'both',
    region: 'US',
    country: 'US',
    language: 'en',
    description: 'Small business data, disaster loans, economic indicators.',
    tier: 4,
    checkFrequency: 'monthly',
  },
  {
    name: 'SBA Office of Advocacy',
    url: 'https://advocacy.sba.gov/',
    type: 'government',
    category: 'both',
    region: 'US',
    country: 'US',
    language: 'en',
    description: 'Small business statistics, research, and data.',
    tier: 4,
    checkFrequency: 'monthly',
  },
  {
    name: 'SBA Size Standards',
    url: 'https://www.sba.gov/size-standards',
    type: 'government',
    category: 'both',
    region: 'US',
    country: 'US',
    language: 'en',
    description:
      'Industry employment thresholds — context for small business layoffs.',
    tier: 4,
    checkFrequency: 'monthly',
  },

  // ============================================================
  // USITC
  // ============================================================
  {
    name: 'USITC Open Data Portal',
    url: 'https://www.usitc.gov/data/index.htm',
    type: 'government',
    category: 'both',
    region: 'US',
    country: 'US',
    language: 'en',
    description: 'Trade data, industry analysis.',
    tier: 4,
    checkFrequency: 'monthly',
  },
  {
    name: 'USITC DataWeb (Trade & Tariff Data)',
    url: 'https://dataweb.usitc.gov/',
    type: 'government',
    category: 'both',
    region: 'US',
    country: 'US',
    language: 'en',
    description: 'US trade and tariff data lookup.',
    tier: 4,
    checkFrequency: 'monthly',
  },
  {
    name: 'USITC Research & Analysis',
    url: 'https://www.usitc.gov/research_and_analysis.htm',
    type: 'government',
    category: 'both',
    region: 'US',
    country: 'US',
    language: 'en',
    description: 'Summary of reports, industry investigations.',
    tier: 4,
    checkFrequency: 'monthly',
  },
  {
    name: 'USITC Office of Economics',
    url: 'https://www.usitc.gov/offices/econ',
    type: 'government',
    category: 'both',
    region: 'US',
    country: 'US',
    language: 'en',
    description: 'Economic impact modeling, trade policy analysis.',
    tier: 4,
    checkFrequency: 'monthly',
  },
  {
    name: 'USITC Section 232/301 Tariff Impact',
    url: 'https://www.usitc.gov/publications/332/pub5405.pdf',
    type: 'government',
    category: 'both',
    region: 'US',
    country: 'US',
    language: 'en',
    description: 'Economic impact of tariffs on industries/workforce.',
    tier: 4,
    checkFrequency: 'monthly',
  },
  {
    name: 'USITC General Factfinding Investigations',
    url: 'https://www.usitc.gov/keywords/general_factfinding_investigations',
    type: 'government',
    category: 'both',
    region: 'US',
    country: 'US',
    language: 'en',
    description: 'Trade-related industry investigations.',
    tier: 4,
    checkFrequency: 'monthly',
  },
];
